version: '3.3'

services:
  api:
    network_mode: host
    build:
      context: src/api/
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 9000:9000
  # ui:
  #   build:
  #     context: .
  #     dockerfile: ui/Dockerfile
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./:/var/app
  #   working_dir: /var/app
  #   ports:
  #     - 8000:8000